### ISSUE TITLE
Build were failed using v1.1.37

### ISSUE THREAD

**Issue by ansidev** [astro-community/astro-compress#113]
```
> astro-starter-template@1.0.4 dev /Users/mac/projects/astro-basic-template
> astro dev

09:00:00 AM [astro] Unable to load /Users/mac/projects/astro-basic-template/astro.config.mjs

 error   Failed to resolve entry for package "astro-compress". The package may have incorrect main/module/exports specified in its package.json.
  File:
    /Users/mac/projects/astro-basic-template/astro.config.mjs
  Stacktrace:
Error: Failed to resolve entry for package "astro-compress". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:23266:11)
    at resolvePackageEntry (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:23263:5)
    at tryNodeResolve (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:23000:20)
    at Context.resolveId (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:22762:28)
    at Object.resolveId (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:43314:46)
    at async TransformContext.resolve (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:43043:23)
    at async normalizeUrl (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:41370:34)
    at async TransformContext.transform (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:41512:47)
    at async Object.transform (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:43387:30)
    at async loadAndTransform (file:///Users/mac/projects/astro-basic-template/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:41105:29)
```

PR: https://github.com/ansidev/astro-basic-template/pull/133

**Comment by nikolaxhristov** [comment]
Fixed in `1.1.39` https://github.com/astro-community/astro-compress/releases/tag/v1.1.39

`1.1.37` and `1.1.38` have been deprecated
